[workspace]
members  = [".", "wmod"]
resolver = "2"

[package]
name = "Whatever"
version = "0.1.0"
edition = "2024"

[dependencies]
winit          = "0.30"
wgpu           = "22"
bytemuck       = { version = "1", features = ["derive"] }
glam           = "0.29"
image          = { version = "0.25", default-features = false, features = ["png"] }
serde          = { version = "1", features = ["derive"] }
toml           = "0.8"
serde_json     = "1"
tokio          = { version = "1", features = ["full"] }
anyhow         = "1"
tracing        = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
semver         = { version = "1", features = ["serde"] }
thiserror      = "1"
dirs           = "5"
base64         = "0.22"
egui = "0.29"
egui-wgpu = "0.29"
egui-winit = "0.29"

[profile.dev]
opt-level = 1
