name: Publish Package to npm

on:
  release:
    types:
      - published
  repository_dispatch:
    types:
      - publish-npm
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    environment: npm-publish

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: "https://registry.npmjs.org"
          token: "${{ github.server_url == 'https://github.com' && github.token || '' }}"

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies and build runtime
        run: bun install --cwd runtime

      - name: Publish to npm
        run: cd runtime && npm publish --access public